Haver/Models/NCR.cs
using Microsoft.Build.ObjectModelRemoting;
using System.ComponentModel.DataAnnotations;
using Haver.DraftModels;

namespace Haver.Models
{
    public class NCR : Auditable
    {
        public int ID { get; set; }

        [Display(Name = "NCR number")]
        public string NCRNum { get; set; }

        public bool IsNCRArchived { get; set; }

        public bool ExpecDateReturnReminded { get; set; }

        public bool IsNCRDraft { get; set; }

        [Display(Name = "Voiding reason")]
        public string VoidingReason { get; set; }

        [Display(Name = "Status")]
        public string Status { get; set; }

        [Display(Name = "Phase")]
        public string Phase { get; set; }    

        [Display(Name = "Created on DateOnly")]
        public DateOnly CreatedOnDO { get; set; }

        [ScaffoldColumn(false)]
        [Timestamp]
        public Byte[] RowVersion { get; set; }//Added for concurrency

        public QualityRepresentative QualityRepresentative { get; set; }
        public Engineering Engineering { get; set; }
        public Operations Operations { get; set; }
        public Procurement Procurement { get; set; }
        public Reinspection Reinspection { get; set; }

        public int? QualityRepresentativeID { get; set; }
        public int? EngineeringID { get; set; }
        public int? OperationsID { get; set; }
        public int? ProcurementID { get; set; }
        public int? ReinspectionID { get; set; }

        public int? PrevNCRID { get; set; }
        public int? NewNCRID { get; set; }

        //Draft models
        public DraftQualityRepresentative DraftQualityRepresentative { get; set; }
        public DraftEngineering DraftEngineering { get; set; }
        public DraftOperations DraftOperations { get; set; }
        public DraftProcurement DraftProcurement { get; set; }
        public DraftReinspection DraftReinspection { get; set; }

        public int? DraftQualityRepresentativeID { get; set; }
        public int? DraftEngineeringID { get; set; }
        public int? DraftOperationsID { get; set; }
        public int? DraftProcurementID { get; set; }
        public int? DraftReinspectionID { get; set; }
    }
}

Haver/Controllers/NCRController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Haver.Data;
using Haver.Models;
using Haver.DraftModels;
using Haver.ViewModels;
using static System.Runtime.InteropServices.JavaScript.JSType;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Haver.Utilities;
using Microsoft.AspNetCore.Identity.UI.Services;
using System.Net.Mail;
using OfficeOpenXml.FormulaParsing.Excel.Functions.Math;
using System.Xml.Linq;
using iTextSharp.text.pdf;
using iTextSharp.text;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using OfficeOpenXml.FormulaParsing.Excel.Functions.Text;
using SQLitePCL;
using System.Reflection;
using System.ComponentModel.DataAnnotations;
using NuGet.Packaging;
using Microsoft.AspNetCore.CookiePolicy;
using OfficeOpenXml.Packaging.Ionic.Zip;
using Org.BouncyCastle.Asn1.X509;
using OfficeOpenXml.FormulaParsing.Excel.Functions.DateTime;
using NuGet.DependencyResolver;
using Microsoft.AspNetCore.Routing.Template;
using System.Diagnostics;
using QuestPDF.Fluent;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.SqlServer.Query.Internal;
using Microsoft.AspNetCore.Http;
using Haver.CustomControllers;
using Microsoft.EntityFrameworkCore.Storage;
using Org.BouncyCastle.Crypto.Signers;
using Org.BouncyCastle.Utilities.Encoders;
using System.Data;
using Microsoft.AspNetCore.Components.Routing;
using System.Composition;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using SixLabors.ImageSharp.Formats;
using Image = SixLabors.ImageSharp.Image;

namespace Haver.Controllers
{
    [Authorize]
    public class NCRController : ElephantController
    {
        private readonly IMyEmailSender _emailSender;
        private readonly HaverContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public NCRController(HaverContext context, IMyEmailSender emailSender, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _emailSender = emailSender;
            _userManager = userManager;
        }

        //GET: NCR
        public async Task<IActionResult> Index(string ncrsByActiveTime, string SearchString, string SupplierID, int? page, int? pageSizeID, string SelectedOption
            , string actionButton, string active, string sortDirection = "desc", string sortField = "CREATED ON")
        {

            PopulateList();

            ViewData["activeCheck"] = active;

            int? supSelected = null;

            if (SupplierID != null)
            {
                try
                {
                    int indexSup = SupplierID.IndexOf(' ');
                    string supCode = SupplierID.Substring(0, indexSup);
                    var getSup = _context.Suppliers.FirstOrDefault(p => p.SupplierCode == Convert.ToInt32(supCode));
                    if(getSup != null)
                    {
                        supSelected = getSup.ID;
                    }
                }
                catch (Exception)
                {

                }
            }
            if (SupplierID != null)
            {
                ViewData["SupplierSelected"] = SupplierID;
            }
            if(SearchString != null)
            {
                ViewData["NcrNumSelected"] = SearchString;
            }
            

            //Dropdown data
            var ncrsDL = _context.NCRs.ToList();
            ViewBag.NCRsToDL = ncrsDL;

            string[] sortOptions = new[] { "NCR NO.", "CREATED ON" };

            var haverContext = _context.NCRs.Include(n => n.Engineering)
                                            .Include(n => n.Operations)
                                            .Include(n => n.QualityRepresentative)
                                                .Include(n => n.QualityRepresentative.Problem)
                                                .Include(n => n.QualityRepresentative.Supplier)
                                            .Include(n => n.Procurement)
                                            .Include(n => n.Reinspection)
                                            .Where(n => !n.IsNCRArchived)
                                            .AsNoTracking();

            //Create time variables for each "orverdue period"
            var nowToronto = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time"));
            var threeDaysAgo = nowToronto.AddDays(-3).Date;
            var twoDaysAgo = nowToronto.AddDays(-2).Date;
            var oneDayAgo = nowToronto.AddDays(-1).Date;


            if (supSelected.HasValue)
            {
                haverContext = haverContext.Where(p => p.QualityRepresentative.SupplierID == supSelected);
            }
            if (!string.IsNullOrEmpty(SearchString))
            {
                haverContext = haverContext.Where(p => p.NCRNum.Contains(SearchString));
            }
            if (!string.IsNullOrEmpty(SelectedOption))
            {
                haverContext = haverContext.Where(p => p.Phase.Contains(SelectedOption));
            }
            if (active == null)
            {
                haverContext = haverContext.Where(p => p.Status.Contains("Active"));
            }
            if (active != null)
            {
                haverContext = haverContext.Where(p => p.ID != null);
            }
            if (ncrsByActiveTime != null)
            {
                //Fieltering overdue NCRs, by time and by phase
                if (ncrsByActiveTime == "+3d")
                {
                    List<NCR> ncrsToDisplay = new List<NCR>();
                    if(haverContext.Count() > 0)
                    {
                        try
                        {
                            foreach (var ncr in haverContext)
                            {
                                TimeSpan differenceLastFilled = (TimeSpan)(nowToronto - ncr.CreatedOn);
                                if (SelectedOption == "Quality Representative")
                                {
                                    differenceLastFilled = (TimeSpan)(nowToronto - ncr.CreatedOn);
                                }
                                else if (SelectedOption == "Engineering")
                                {
                                    differenceLastFilled = (TimeSpan)(nowToronto - ncr.QualityRepresentative.CreatedOn);
                                }
                                else if (SelectedOption == "Operations")
                                {
                                    if (ncr.Engineering != null && ncr.QualityRepresentative.ConfirmingEng == false)
                                    {
                                        differenceLastFilled = (TimeSpan)(nowToronto - ncr.Engineering.CreatedOn);
                                    }
                                    else if(ncr.Engineering == null && ncr.QualityRepresentative.ConfirmingEng == true)
                                    {
                                        differenceLastFilled = (TimeSpan)(nowToronto - ncr.QualityRepresentative.CreatedOn);
                                    }
                                }
                                else if (SelectedOption == "Procurement")
                                {
                                    differenceLastFilled = (TimeSpan)(nowToronto - ncr.Operations.CreatedOn);
                                }
                                else if (SelectedOption == "Reinspection")
                                {
                                    differenceLastFilled = (TimeSpan)(nowToronto - ncr.Procurement.CreatedOn);
                                }

                                var LastFilled = differenceLastFilled.Days;

                                if (LastFilled > 2)
                                {
                                    ncrsToDisplay.Add(ncr);
                                }
                            }
                        }
                        catch(Exception ex)
                        {

                        }
                        haverContext = haverContext.Where(ncr => ncrsToDisplay.Contains(ncr));
                    }

                }
                else if (ncrsByActiveTime == "48h")
                {
                    List<NCR> ncrsToDisplay = new List<NCR>();
                    if (haverContext.Count() > 0)
                    {
                        foreach (var ncr in haverContext)
                        {
                            try
                            {
                                TimeSpan differenceLastFilled = (TimeSpan)(nowToronto - ncr.CreatedOn);
                                if (SelectedOption == "Quality Representative")
                                {
                                    differenceLastFilled = (TimeSpan)(nowToronto - ncr.CreatedOn);
                                }
                                else if (SelectedOption == "Engineering")
                                {
                                    differenceLastFilled = (TimeSpan)(nowToronto - ncr.QualityRepresentative.CreatedOn);
                                }
                                else if (SelectedOption == "Operations")
                                {
                                    if (ncr.QualityRepresentative.ConfirmingEng == true)
                                    {
                                        differenceLastFilled = (TimeSpan)(nowToronto - ncr.QualityRepresentative.CreatedOn);
                                    }
                                    else
                                    {

Haver/Views/NCR/Archived.cshtml
@model IEnumerable<NCR>

@{
    ViewData["Title"] = "Archived";

    var activeCheck = ViewData["activeCheck"] as string;

    var supplierSelected = ViewData["SupplierSelected"] as string;
    var ncrNumSelected = ViewData["NcrNumSelected"] as string;
}

<div>
    <h1>NCR</h1>

    <nav class="main-nav ncr navbar-expand-sm navbar-toggleable-sm">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="NCR" asp-action="Index" onclick="activateLink(this)">NCR log</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="NCR" asp-action="Analytics" onclick="activateLink(this)">Analytics</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="NCR" asp-action="Archived" onclick="activateLink(this)">Archived NCRs</a>
                <hr />
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="NCR" asp-action="Archiving" onclick="activateLink(this)">Bulk Archiving</a>
            </li>

        </ul>
        <hr />

    </nav>
    <div class="dropdown ncr-mobile-nav">
        <button class="dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="bi bi-list"></i>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
            <li><a class="nav-link" asp-area="" asp-controller="NCR" asp-action="Index" onclick="activateLink(this)">NCR log</a></li>
            <li><a class="nav-link" asp-area="" asp-controller="NCR" asp-action="Analytics" onclick="activateLink(this)">Analytics</a></li>
            <li><a class="nav-link" asp-area="" asp-controller="NCR" asp-action="Archived" onclick="activateLink(this)">Archived NCRs</a></li>
            <li><a class="nav-link" asp-area="" asp-controller="NCR" asp-action="Archiving" onclick="activateLink(this)">Bulk Archiving</a></li>
        </ul>
        <h2>Archived</h2>
        <hr />
    </div>
</div>

<form asp-action="Archived" method="get">
    <input type="hidden" name="sortDirection" value="@ViewData["sortDirection"]" />
    <input type="hidden" name="sortField" value="@ViewData["sortField"]" />

    <div class="archived filtering-fields form-horizontal">
        <div class="row">
            <div class="form-group col-md-3">
                <label class="control-label">Search by NCR number</label>
                <div class="input-search-box">
                    <input name="SearchString" class="form-control" list="datalistOptions" id="exampleDataList" placeholder="Search NCR number" autocomplete="off" type="text" value="@ncrNumSelected">
                </div>
                <datalist id="datalistOptions">
                    @foreach (var ncr in ViewBag.NCRsToDL)
                    {
                        <option value="@ncr.NCRNum"></option>
                    }
                </datalist>
            </div>
            <div class="form-group col-md-3">
                <label class="control-label">Start Date</label>
                <input type="date" class="form-control" name="startDate">
            </div>
            <div class="form-group col-md-3">
                <label class="control-label">End Date</label>
                <input type="date" class="form-control" name="endDate">
            </div>
            <div class="form-group col-md-3">
                <label class="control-label">Filter by Supplier</label>
                <div class="input-search-box">
                    <input name="SupplierID" class="form-control" list="supOptions" id="exampleDataListTwo" placeholder="Search supplier" autocomplete="off" type="text" value="@supplierSelected">
                </div>
                <datalist id="supOptions">
                    @foreach (var item in ViewBag.SupplierSummary)
                    {
                        <option value="@item.Value">@item.Text</option>
                    }
                </datalist>
            </div>
            <div class="form-group col-md-4 align-self-end fieltering-btns">
                <button asp-action="Archived" formmethod="get" type="submit" name="actionButton" class="btn btn-primary">
                    <i class="bi bi-funnel-fill"></i>
                    Filter
                </button>
                <a asp-action="Archived" class="btn btn-primary"><i class="bi bi-arrow-clockwise"></i>Clear</a>
            </div>
        </div>
    </div>

    <div class="d-none d-lg-block">
    
        <table class="table table-borderless">
            <thead>
                <tr>
                    <th class="sorting-headers">
                        <input id="thElement" type="submit" name="actionButton" value="NCR NO." class="btn btn-link" />
                        <i class="bi bi-arrow-down-up "></i>
                    </th>
                    <th>
                        STATUS
                    </th>
                    <th>
                        PHASE
                    </th>
                    <th class="pono-row-header">
                        PO OR PROD NO.
                    </th>
                    <th>
                        SUPPLIER
                    </th>
                    <th class="sorting-headers">
                        <input type="submit" name="actionButton" value="CREATED ON" class="btn btn-link" />
                        <i class="bi bi-arrow-down-up"></i>
                    </th>

                    <th></th>
                </tr>
            </thead>

            <tbody class="ncr-list-row">
                @foreach (var item in Model)
                {

                    <tr id="tr-@item.ID">
                        <td class="ncr-num-td">
                            @if (item.NCRNum == null)
                            {
                                <div>0000-000</div>
                            }
                            else
                            {
                                <div>@Html.DisplayFor(modelItem => item.NCRNum)</div>
                            }
                        </td>
                        <td>
                            <span style="color: var(--haver-blue);">Archived</span>
                        </td>
                        <td class="ncr-row-phase">
                            @Html.DisplayFor(modelItem => item.Phase)
                        </td>
                        <td class="pono-row">
                            @Html.DisplayFor(modelItem => item.QualityRepresentative.PoNo)
                        </td>
                        <td class="supplier-name-row">
                            @Html.DisplayFor(modelItem => item.QualityRepresentative.Supplier.SupplierName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CreatedOnDO)
                        </td>
                        <td class="details-menu-row">

                            <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.ID"><i class="bi bi-card-list"></i>Details</a>
                            @* <a class="btn btn-primary" href="@Url.Action("DownloadPDF", "NCR", new { id = @item.ID })"><i class="bi bi-download"></i>Download PDF</a> *@
                            <div class="dropdown">
                                <button class="dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-three-dots-vertical"></i>
                                </button>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">

                                    @if (item.PrevNCRID != null)
                                    {
                                        <li><a class="dropdown-item" asp-action="Details" asp-route-id="@item.PrevNCRID">Go to prev NCR</a></li>
                                    }
                                    <li><a class="dropdown-item" asp-action="Details" asp-route-id="@item.ID">Details</a></li>
                                    <li><a class="dropdown-item" href="@Url.Action("DownloadPDF", "NCR", new { id = @item.ID })">Download PDF</a></li>

                                </ul>
                            </div>
                        </td>
                        @if (item.PrevNCRID != null)
                        {
                            <script>
                                document.querySelectorAll('#tr-' + @item.ID + ' td').forEach((td, index) => {
                                    // Setting common styles for border bottom and top
                                    td.style.borderBottom = '1.5px rgb(175, 57, 57, 54%) solid';
                                    td.style.borderTop = '1.5px rgb(175, 57, 57, 54%) solid';

                                    if (index === 6) {
                                            td.style.borderRight = '1.5px rgb(175, 57, 57, 54%) solid';
                                    }
                                    if (index === 0) {
                                        td.style.borderLeft = '1.5px rgb(175, 57, 57, 54%) solid';
                                    }

                                });

                            </script>
                        }
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <br />
    <div class="ncr-cards container-fluid d-block d-lg-none">

        <div class="row">
            @foreach (var item in Model)
            {
                <div class="card mb-3">
                    <div class="card-header">
                        @if (item.NCRNum == null)
                        {
                            <p>0000-000</p>
                        }
                        else
                        {
                            <p>@Html.DisplayFor(modelItem => item.NCRNum)</p>
                        }
                        @if (item.Status == "Active")
                        {
                            <span style="color: var(--green);">@Html.DisplayFor(modelItem => item.Status)</span>
                        }
                        else if (item.Status == "Closed")
                        {
                            <span style="color: var(--yellow);">@Html.DisplayFor(modelItem => item.Status)</span>
                        }
                        else if (item.Status == "Rejected" || item.Status == "Rejected Again")
                        {
                            <span style="color: var(--red);">@Html.DisplayFor(modelItem => item.Status)</span>
                        }
                        else if (item.Status == "Voided")
                        {
                            <span style="color: var(--haver-blue);">@Html.DisplayFor(modelItem => item.Status)</span>
                        }
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col">
                                <p><strong>Phase:</strong> @Html.DisplayFor(modelItem => item.Phase)</p>
                                <p><strong>PO Number:</strong> @Html.DisplayFor(modelItem => item.QualityRepresentative.PoNo)</p>
                                <p><strong>Supplier:</strong> @Html.DisplayFor(modelItem => item.QualityRepresentative.Supplier.SupplierName)</p>
                                <p><strong>Created On:</strong> @Html.DisplayFor(modelItem => item.CreatedOn)</p>
                            </div>
                            <div class="col">
                                @if (item.PrevNCRID != null)
                                {

                                    <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.PrevNCRID">Go to prev NCR</a>
                                }
                                <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.ID">Details</a>
                                <a class="btn btn-primary" href="@Url.Action("DownloadPDF", "NCR", new { id = @item.ID })">Download PDF</a>
                            </div>
                        </div>
                    </div>
                </div>

            }

        </div>

    </div>

    <partial name="_PagingNavBar" />
</form>

Haver/Views/NCR/Delete.cshtml
@model NCR

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NCR</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phase)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NCRNum)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NCRNum)
        </dd>

    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>