Haver/Models/EngReview.cs
using Haver.DraftModels;
using System.ComponentModel.DataAnnotations;

namespace Haver.Models
{
    public class EngReview
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Review is required.")]
        [Display(Name = "Engineering Review")]
        [StringLength(255, ErrorMessage = "Review is limited to 255 characters.")]
        public string Review { get; set; }

        public ICollection<Engineering> Engineerings { get; set; } = new HashSet<Engineering>();
    }
}

Haver/Models/Part.cs
using Haver.DraftModels;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;

namespace Haver.Models
{
    public class Part
    {
        public int ID { get; set; }

        public string PartSummary
        {
            get
            {
                return $"{PartNumber} - {PartDesc}";
            }
        }

        [Display(Name = "Part Number")]
        [Required(ErrorMessage = "Part Number is Required")]
        public int PartNumber { get; set; }

        [Display(Name = "Part Description")]
        [Required(ErrorMessage = "Part Description is Required")]
        public string PartDesc { get; set; }

        public ICollection<QualityRepresentative> QualityRepresentatives { get; set; } = new HashSet<QualityRepresentative>();
    }
}

Haver/Models/PrelDecision.cs
using Haver.DraftModels;
using System.ComponentModel.DataAnnotations;

namespace Haver.Models
{
    public class PrelDecision
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Preliminary Decision is required.")]
        [Display(Name = "Preliminary Decision")]
        [StringLength(255, ErrorMessage = "Decision is limited to 255 characters.")]
        public string Decision { get; set; }

        public ICollection<Operations> OperationsS { get; set; } = new HashSet<Operations>();
    }
}

Haver/Controllers/PartsController.cs
using Haver.CustomControllers;
using System.Numerics;
using Microsoft.AspNetCore.Authorization;
using Haver.Data;
using Haver.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using OfficeOpenXml;
using Org.BouncyCastle.Utilities.Encoders;


namespace Haver.Controllers
{
    [Authorize(Roles = "Admin,Quality Inspector")]
    public class PartController : LookupsController
    {
        private readonly HaverContext _context;

        public PartController(HaverContext context)
        {
            _context = context;
        }

        // GET: Part
        public IActionResult Index()
        {

            return Redirect(ViewData["returnURL"].ToString());
        }

        // GET: Part/Create
        public IActionResult Create()
        {

            return View();
        }

        // POST: Part/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,PartDesc, PartNumber")] Part Part)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(Part);
                    await _context.SaveChangesAsync();
                    return Redirect(ViewData["returnURL"].ToString());
                }
            }
            catch (DbUpdateException dex)
            {
                if (dex.GetBaseException().Message.Contains("UNIQUE constraint failed"))
                {
                    ModelState.AddModelError("", "Unable to save changes. Part number alredy exists.");
                }
                else
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }
            }

            return View(Part);
        }

        // GET: Part/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Parts == null)
            {
                return NotFound();
            }

            var Part = await _context.Parts.FindAsync(id);
            if (Part == null)
            {
                return NotFound();
            }
            return View(Part);
        }

        // POST: Part/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            var PartToUpdate = await _context.Parts
                .FirstOrDefaultAsync(m => m.ID == id);

            //Check that you got it or exit with a not found error
            if (PartToUpdate == null)
            {
                return NotFound();
            }

            //Try updating it with the values posted
            if (await TryUpdateModelAsync<Part>(PartToUpdate, "", d => d.PartNumber,
                d => d.PartDesc))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    return Redirect(ViewData["returnURL"].ToString());
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PartExists(PartToUpdate.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "The record you attempted to edit "
                        + "was modified by another user. Please go back and refresh.");
                    }
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }
            }
            return View(PartToUpdate);
        }

        // GET: Part/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Parts == null)
            {
                return NotFound();
            }

            var Part = await _context.Parts
                .FirstOrDefaultAsync(m => m.ID == id);
            if (Part == null)
            {
                return NotFound();
            }

            return View(Part);
        }

        // POST: Part/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Parts == null)
            {
                return Problem("Entity set 'HaverContext.Parts'  is null.");
            }
            var Part = await _context.Parts
               .FirstOrDefaultAsync(m => m.ID == id);
            try
            {
                if (Part != null)
                {
                    _context.Parts.Remove(Part);
                }
                await _context.SaveChangesAsync();
                return Redirect(ViewData["returnURL"].ToString());
            }
            catch (DbUpdateException dex)
            {
                if (dex.GetBaseException().Message.Contains("FOREIGN KEY constraint failed"))
                {
                    ModelState.AddModelError("", "Unable to Delete " + ViewData["ControllerFriendlyName"] +
                        ". Remember, you cannot delete a " + ViewData["ControllerFriendlyName"] + " that has related records.");
                }
                else
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }
            }
            return View(Part);

        }

        [HttpPost]
        public async Task<IActionResult> InsertFromExcel(IFormFile theExcel)
        {
            string feedBackGreen = string.Empty;
            string feedBack = string.Empty;
            if (theExcel != null)
            {
                string mimeType = theExcel.ContentType;
                long fileLength = theExcel.Length;
                if (!(mimeType == "" || fileLength == 0))//Looks like we have a file!!!
                {
                    if (mimeType.Contains("excel") || mimeType.Contains("spreadsheet"))
                    {
                        ExcelPackage excel;
                        using (var memoryStream = new MemoryStream())
                        {
                            await theExcel.CopyToAsync(memoryStream);
                            excel = new ExcelPackage(memoryStream);
                        }
                        var workSheet = excel.Workbook.Worksheets[0];
                        var start = workSheet.Dimension.Start;
                        var end = workSheet.Dimension.End;
                        int successCount = 0;
                        int errorCount = 0;
                        List<string> partsWithSupplierNull = new List<string>();
                        if (workSheet.Cells[1, 1].Text == "Part Description" &&
                            workSheet.Cells[1, 2].Text == "Part Number" &&
                            workSheet.Cells[1, 3].Text == "Supplier Name")
                        {
                            for (int row = start.Row + 1; row <= end.Row; row++)
                            {
                                Part p = new Part();
                                try
                                {
                                    // Row by row...
                                    p.PartDesc = workSheet.Cells[row, 1].Text;
                                    p.PartNumber = workSheet.Cells[row, 2].GetValue<int>();

                                    _context.Parts.Add(p);
                                    _context.SaveChanges();
                                    successCount++;
                                }
                                catch (DbUpdateException dex)
                                {
                                    errorCount++;
                                    if (dex.GetBaseException().Message.Contains("UNIQUE constraint failed"))
                                    {
                                        feedBack += "Error: Part " + p.PartNumber + " was rejected as a duplicate."
                                                + "<br />";
                                    }
                                    else
                                    {
                                        feedBack += "Error: Record " + p.PartNumber + " caused an error."
                                                + "<br />";
                                    }
                                    //Here is the trick to using SaveChanges in a loop.  You must remove the 
                                    //offending object from the cue or it will keep raising the same error.
                                    _context.Remove(p);
                                }
                                catch (Exception ex)
                                {
                                    errorCount++;
                                    if (ex.GetBaseException().Message.Contains("correct format"))
                                    {
                                        feedBack += "Error: Record " + p.PartNumber + " was rejected because the number was not in the correct format."
                                                + "<br />";
                                    }
                                    else
                                    {

Haver/Controllers/PrelDecisionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Haver.Data;
using Haver.Models;
using Haver.CustomControllers;
using System.Numerics;
using Microsoft.AspNetCore.Authorization;


namespace Haver.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PrelDecisionController : LookupsController
    {
        private readonly HaverContext _context;

        public PrelDecisionController(HaverContext context)
        {
            _context = context;
        }

        // GET: PrelDecision
        public IActionResult Index()
        {
            return Redirect(ViewData["returnURL"].ToString());
        }

        // GET: PrelDecision/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: PrelDecision/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Decision")] PrelDecision PrelDecision)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(PrelDecision);
                    await _context.SaveChangesAsync();
                    return Redirect(ViewData["returnURL"].ToString());
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
            }

            return View(PrelDecision);
        }

        // GET: PrelDecision/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PrelDecisions == null)
            {
                return NotFound();
            }

            var PrelDecision = await _context.PrelDecisions.FindAsync(id);
            if (PrelDecision == null)
            {
                return NotFound();
            }
            return View(PrelDecision);
        }

        // POST: PrelDecision/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            var PrelDecisionToUpdate = await _context.PrelDecisions
                .FirstOrDefaultAsync(m => m.ID == id);

            //Check that you got it or exit with a not found error
            if (PrelDecisionToUpdate == null)
            {
                return NotFound();
            }

            //Try updating it with the values posted
            if (await TryUpdateModelAsync<PrelDecision>(PrelDecisionToUpdate, "",
                d => d.Decision))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    return Redirect(ViewData["returnURL"].ToString());
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PrelDecisionExists(PrelDecisionToUpdate.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }
            }
            return View(PrelDecisionToUpdate);
        }

        // GET: PrelDecision/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PrelDecisions == null)
            {
                return NotFound();
            }

            var PrelDecision = await _context.PrelDecisions
                .FirstOrDefaultAsync(m => m.ID == id);
            if (PrelDecision == null)
            {
                return NotFound();
            }

            return View(PrelDecision);
        }

        // POST: PrelDecision/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PrelDecisions == null)
            {
                return Problem("Entity set 'HaverContext.PrelDecisions'  is null.");
            }
            var PrelDecision = await _context.PrelDecisions
               .FirstOrDefaultAsync(m => m.ID == id);
            try
            {
                if (PrelDecision != null)
                {
                    _context.PrelDecisions.Remove(PrelDecision);
                }
                await _context.SaveChangesAsync();
                return Redirect(ViewData["returnURL"].ToString());
            }
            catch (DbUpdateException dex)
            {
                if (dex.GetBaseException().Message.Contains("FOREIGN KEY constraint failed"))
                {
                    ModelState.AddModelError("", "Unable to Delete " + ViewData["ControllerFriendlyName"] +
                        ". Remember, you cannot delete a " + ViewData["ControllerFriendlyName"] + " that has related records.");
                }
                else
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                }
            }
            return View(PrelDecision);

        }

        private bool PrelDecisionExists(int id)
        {
            return _context.PrelDecisions.Any(e => e.ID == id);
        }
    }
}

Haver/Views/Lookup/Index.cshtml
@{
    ViewData["Title"] = "Lookups";
}


<div>
    <h1>Lookups</h1>

    <div class="text-success">@Html.Raw(TempData["FeedbackGreen"])</div>
    <div class="text-danger">@Html.Raw(TempData["Feedback"])</div>

    <!-- Nav tabs -->
    <nav class="main-nav lookups-nav navbar-expand-sm navbar-toggleable-sm">
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <button class="nav-link active" id="Information-Tab" data-bs-toggle="tab" data-bs-target="#InformationPanel" type="button" role="tab" aria-controls="InformationPanel" aria-selected="true">Information</button>
            <button class="nav-link" id="EngReview-Tab" data-bs-toggle="tab" data-bs-target="#EngReviewPanel" type="button" role="tab" aria-controls="EngReviewPanel" aria-selected="false">Eng. Reviews</button>
            <button class="nav-link" id="Part-Tab" data-bs-toggle="tab" data-bs-target="#PartPanel" type="button" role="tab" aria-controls="PartPanel" aria-selected="false">Parts</button>
            <button class="nav-link" id="Problem-Tab" data-bs-toggle="tab" data-bs-target="#ProblemPanel" type="button" role="tab" aria-controls="ProblemPanel" aria-selected="false">Problems</button>
            <button class="nav-link" id="PrelDecision-Tab" data-bs-toggle="tab" data-bs-target="#PrelDecisionPanel" type="button" role="tab" aria-controls="PrelDecisionPanel" aria-selected="false">Prel. Decisions</button>
            <button class="nav-link" id="Supplier-Tab" data-bs-toggle="tab" data-bs-target="#SupplierPanel" type="button" role="tab" aria-controls="SupplierPanel" aria-selected="false">Suppliers</button>
        </div>
        <hr />
    </nav>

    <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="InformationPanel" role="tabpanel" aria-labelledby="InformationTab">
            <p>This page will allow you to manage all of the Lookup values in the system. </p><p>
                Just select a Tab to view and maintiain the values for a specific one.
            </p>
        </div>
        <div class="tab-pane fade" id="EngReviewPanel" role="tabpanel" aria-labelledby="EngReview-Tab"><br /></div>
        <div class="tab-pane fade" id="PartPanel" role="tabpanel" aria-labelledby="Part-Tab"><br /></div>
        <div class="tab-pane fade" id="ProblemPanel" role="tabpanel" aria-labelledby="Problem-Tab"><br /></div>
        <div class="tab-pane fade" id="PrelDecisionPanel" role="tabpanel" aria-labelledby="PrelDecisionPanel-Tab"><br /></div>
        <div class="tab-pane fade" id="SupplierPanel" role="tabpanel" aria-labelledby="Supplier-Tab"><br /></div>
    </div>

</div>


@section Scripts {
    <script type="text/javascript">

        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
            return new bootstrap.Tooltip(tooltipTriggerEl)
        })

        function refreshTab(activeTab) {
            switch (activeTab) {
                case 'EngReview-Tab': $('#EngReviewPanel').load('/Lookup/EngReview');
                    break;
                case 'PrelDecision-Tab': $('#PrelDecisionPanel').load('/Lookup/PrelDecision');
                    break;
                case 'Part-Tab': $('#PartPanel').load('/Lookup/Part');
                    break;
                case 'Problem-Tab': $('#ProblemPanel').load('/Lookup/Problem');
                    break;
                case 'Supplier-Tab': $('#SupplierPanel').load('/Lookup/Supplier');
                    break;
                default: break;
            };
            return;
        };
        $('.nav-link').click(function () {
            var activeTab = $(this).attr("id");
            refreshTab(activeTab);
        });
        $(".tab-content").on("click", ".linkClick", function (event) {
            event.preventDefault();
            var address = $(this).attr("href");
            var lookup = address.split("/")[1];
            var id = $("#" + lookup + "ID").val();
            var caption = $("#" + lookup).html();
            if (id == null) {
                alert("Error: no value selected from the " + caption + " list!");
            } else {
                window.location.href = address + "/" + id;
            }
        });
        $(function () {
            setTimeout(function () {
                $("#@ViewData["Tab"]").trigger('click');
            }, 10);
        });
    </script>
}

Haver/Views/Lookup/_EngReview.cshtml
<div class="card-body">
@*     <form asp-action="InsertFromExcel" asp-controller="EngReview" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label class="control-label custom-file-label">Upload Excel File:</label>
                    <div class="mb-3">
                        <input class="form-control" type="file" id="theExcel" name="theExcel">
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Upload Data" class="btn btn-secondary" />
                </div>
            </div>
            <div class="col-md-7">
                <p>
                    Your excel file must have one column named Review.<br />
                </p>
            </div>
        </div>
    </form> *@
    <div class="card-body lookup-values-displayer">
        @Html.DropDownList("EngReviewID", null, htmlAttributes: new { @size = 6, @class = "form-control" })
    </div>
</div>
<div class="lookup-footer">
    <a class="btn btn-primary" asp-controller="EngReview" asp-action="Create">Create</a>
    <a class="btn btn-primary linkClick" asp-controller="EngReview" asp-action="Edit">Edit</a>
    <a class="btn btn-primary linkClick" asp-controller="EngReview" asp-action="Delete">Delete</a>
</div>

Haver/Views/Lookup/_Part.cshtml
<div class="card-body">
    <form asp-action="InsertFromExcel" asp-controller="Part" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label class="control-label custom-file-label">Upload Excel File:</label>
                    <div class="input-group mb-3">
                        <input type="file" class="form-control" name="theExcel" id="theExcel">
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Upload Data" class="btn btn-secondary" />
                </div>
            </div>
            <div class="col-md-7">
                <p>
                    Your excel file must have three columns, one named Part Description, one named Part Number, and an optional comlumn named Supplier Name.<br />
                    <a href="~/assets/excelFiles/Parts.xlsx" download>
                        Download template excel file
                    </a>
                </p>
            </div>
        </div>

    </form>
    <div class="card-body lookup-values-displayer">
        @Html.DropDownList("PartID", null, htmlAttributes: new { @size = 6, @class = "form-control" })
    </div>
</div>
<div class="lookup-footer">
    <a asp-controller="Part" asp-action="Create" class="btn btn-primary">Create</a>
    <a asp-controller="Part" asp-action="Edit" class="btn btn-primary linkClick">Edit</a>
    <a asp-controller="Part" asp-action="Delete" class="btn btn-primary linkClick">Delete</a>
</div>

Haver/Views/Lookup/_PrelDecision.cshtml
<div class="card-body">
    <div class="card-body lookup-values-displayer">
        @Html.DropDownList("PrelDecisionID", null, htmlAttributes: new { @size = 6, @class = "form-control" })
    </div>
</div>
<div class="lookup-footer">
    <a asp-controller="PrelDecision" asp-action="Create" class="btn btn-primary">Create</a>
    <a asp-controller="PrelDecision" asp-action="Edit" class="btn btn-primary linkClick">Edit</a>
    <a asp-controller="PrelDecision" asp-action="Delete" class="btn btn-primary linkClick">Delete</a>
</div>

Haver/Views/Lookup/_Problem.cshtml
<div class="card-body">
    <form asp-action="InsertFromExcel" asp-controller="Problem" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label class="control-label custom-file-label">Upload Excel File:</label>
                    <div class="input-group mb-3">
                        <input type="file" class="form-control" name="theExcel" id="theExcel">
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Upload Data" class="btn btn-secondary" />
                </div>
            </div>
            <div class="col-md-7">
                <p>
                    Your excel file must have one column named Problem Description.<br />
                    <a href="~/assets/excelFiles/Problems.xlsx" download>
                        Download template excel file
                    </a>
                </p>
            </div>
        </div>
    </form>
    <div class="card-body lookup-values-displayer">
        @Html.DropDownList("ProblemID", null, htmlAttributes: new { @size = 6, @class = "form-control" })
    </div>
</div>
<div class="lookup-footer">
    <a asp-controller="Problem" asp-action="Create" class="btn btn-primary">Create</a>
    <a asp-controller="Problem" asp-action="Edit" class="btn btn-primary linkClick">Edit</a>
    <a asp-controller="Problem" asp-action="Delete" class="btn btn-primary linkClick">Delete</a>
</div>

Haver/Views/Lookup/_Supplier.cshtml
<div class="card-body">
    <form asp-action="InsertFromExcel" asp-controller="Supplier" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label class="control-label custom-file-label">Upload Excel File:</label>
                    <div class="input-group mb-3">
                        <input type="file" class="form-control" name="theExcel" id="theExcel">
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Upload Data" class="btn btn-secondary" />
                </div>
            </div>
            <div class="col-md-7">
                <p>
                    Your excel file must have two columns, one named Supplier Name, and another named Supplier Code.<br />
                    <a href="~/assets/excelFiles/Suppliers.xlsx" download>
                        Download template excel file
                    </a>
                </p>
            </div>
        </div>
    </form>
    <div class="card-body lookup-values-displayer">
        @Html.DropDownList("SupplierID", null, htmlAttributes: new { @size = 6, @class = "form-control" })
    </div>
</div>
<div class="lookup-footer">
    <a asp-controller="Supplier" asp-action="Create" class="btn btn-primary">Create</a>
    <a asp-controller="Supplier" asp-action="Edit" class="btn btn-primary linkClick">Edit</a>
    <a asp-controller="Supplier" asp-action="Delete" class="btn btn-primary linkClick">Delete</a>
</div>